'use strict';
const db = require('../config/db');
const defaults = { required_work_minutes: 480, break_calculation_mode: 'actual_break', fixed_break_minutes: 60, min_break_minutes: 0, max_break_minutes: 60, allow_outside_radius_during_break: 1, auto_checkout_grace_minutes: 5 };

async function ensureAttendancePolicyTables() {
  await db.query(`CREATE TABLE IF NOT EXISTS hrms_attendance_policies (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, scope_type VARCHAR(20) NOT NULL DEFAULT 'global', scope_id BIGINT UNSIGNED NULL, required_work_minutes INT UNSIGNED NOT NULL DEFAULT 480, break_calculation_mode VARCHAR(30) NOT NULL DEFAULT 'actual_break', fixed_break_minutes SMALLINT UNSIGNED NOT NULL DEFAULT 60, min_break_minutes SMALLINT UNSIGNED NOT NULL DEFAULT 0, max_break_minutes SMALLINT UNSIGNED NOT NULL DEFAULT 60, allow_outside_radius_during_break TINYINT(1) NOT NULL DEFAULT 1, auto_checkout_grace_minutes SMALLINT UNSIGNED NOT NULL DEFAULT 5, effective_from DATE NOT NULL, is_active TINYINT(1) NOT NULL DEFAULT 1, created_by BIGINT UNSIGNED NULL, updated_by BIGINT UNSIGNED NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, KEY idx_policy_scope (scope_type,scope_id,effective_from,is_active))`);
  await db.query(`CREATE TABLE IF NOT EXISTS hrms_attendance_policy_audit (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, policy_id BIGINT UNSIGNED NOT NULL, changed_by BIGINT UNSIGNED NULL, action VARCHAR(30) NOT NULL, old_value JSON NULL, new_value JSON NULL, reason VARCHAR(500) NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, KEY idx_policy_audit (policy_id,created_at))`);
  const [rows] = await db.query("SELECT id FROM hrms_attendance_policies WHERE scope_type='global' AND scope_id IS NULL AND is_active=1 LIMIT 1");
  if (!rows.length) await db.query(`INSERT INTO hrms_attendance_policies (scope_type,required_work_minutes,break_calculation_mode,fixed_break_minutes,min_break_minutes,max_break_minutes,allow_outside_radius_during_break,auto_checkout_grace_minutes,effective_from) VALUES ('global',?,?,?,?,?,?,?,CURDATE())`, [480,'actual_break',60,0,60,1,5]);
}
const n = (value, fallback, min, max) => Math.min(max, Math.max(min, Math.round(Number.isFinite(Number(value)) ? Number(value) : fallback)));
function clean(input) { const mode = String(input.break_calculation_mode || defaults.break_calculation_mode); if (!['actual_break','fixed_schedule'].includes(mode)) throw new Error('Invalid break calculation mode'); const min = n(input.min_break_minutes,0,0,480); return { required_work_minutes:n(input.required_work_minutes,480,60,960), break_calculation_mode:mode, fixed_break_minutes:n(input.fixed_break_minutes,60,0,480), min_break_minutes:min, max_break_minutes:n(input.max_break_minutes,60,min,480), allow_outside_radius_during_break:input.allow_outside_radius_during_break === false || input.allow_outside_radius_during_break === 0 ? 0 : 1, auto_checkout_grace_minutes:n(input.auto_checkout_grace_minutes,5,0,120), effective_from:/^\d{4}-\d{2}-\d{2}$/.test(String(input.effective_from||'')) ? input.effective_from : new Date().toISOString().slice(0,10), is_active:input.is_active === false || input.is_active === 0 ? 0 : 1 }; }
async function list(req,res,next) { try { await ensureAttendancePolicyTables(); const [policies] = await db.query('SELECT * FROM hrms_attendance_policies ORDER BY is_active DESC,effective_from DESC,id DESC'); const [audit] = await db.query(`SELECT a.*,e.full_name changed_by_name FROM hrms_attendance_policy_audit a LEFT JOIN employee_users e ON e.id=a.changed_by ORDER BY a.created_at DESC LIMIT 50`); res.json({success:true,data:{policies,audit}}); } catch(error) { next(error); } }
async function save(req,res,next) { try { await ensureAttendancePolicyTables(); const value=clean(req.body||{}); const type=['global','company','department','shift','employee'].includes(String(req.body.scope_type)) ? String(req.body.scope_type) : 'global'; const scopeId=type==='global'?null:n(req.body.scope_id,0,1,Number.MAX_SAFE_INTEGER); if(type!=='global'&&!scopeId)return res.status(400).json({success:false,message:'Select a valid scope record.'}); const id=Number(req.body.id||0); let old=null; if(id){const [rows]=await db.query('SELECT * FROM hrms_attendance_policies WHERE id=?',[id]);if(!rows.length)return res.status(404).json({success:false,message:'Attendance policy not found.'});old=rows[0];await db.query(`UPDATE hrms_attendance_policies SET scope_type=?,scope_id=?,required_work_minutes=?,break_calculation_mode=?,fixed_break_minutes=?,min_break_minutes=?,max_break_minutes=?,allow_outside_radius_during_break=?,auto_checkout_grace_minutes=?,effective_from=?,is_active=?,updated_by=? WHERE id=?`,[type,scopeId,...Object.values(value),req.user.id,id]);}else{const [result]=await db.query(`INSERT INTO hrms_attendance_policies (scope_type,scope_id,required_work_minutes,break_calculation_mode,fixed_break_minutes,min_break_minutes,max_break_minutes,allow_outside_radius_during_break,auto_checkout_grace_minutes,effective_from,is_active,created_by,updated_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)`,[type,scopeId,...Object.values(value),req.user.id,req.user.id]);req.body.id=result.insertId;} const [[saved]]=await db.query('SELECT * FROM hrms_attendance_policies WHERE id=?',[req.body.id||id]); await db.query('INSERT INTO hrms_attendance_policy_audit (policy_id,changed_by,action,old_value,new_value,reason) VALUES (?,?,?,?,?,?)',[saved.id,req.user.id,id?'updated':'created',old?JSON.stringify(old):null,JSON.stringify(saved),String(req.body.reason||'').trim().slice(0,500)||null]);res.json({success:true,data:saved});}catch(error){next(error);} }
module.exports={ensureAttendancePolicyTables,list,save};
