const express = require('express');
const db = require('../config/db');
const { authenticateToken } = require('./auth');
const router = express.Router();

router.use(authenticateToken);
const isAdmin = (req) => ['admin','super_admin'].includes(String(req.user?.role || '').toLowerCase()) || ['admin','super_admin'].includes(String(req.user?.userType || req.user?.user_type || '').toLowerCase()) || [true,1,'1'].includes(req.user?.isMainAdmin) || [true,1,'1'].includes(req.user?.is_main_admin);
async function ensure() {
  await db.query(`CREATE TABLE IF NOT EXISTS hrms_announcements (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,title VARCHAR(180) NOT NULL,message TEXT NOT NULL,category ENUM('festival','important','general','meeting','payroll','policy') NOT NULL DEFAULT 'general',audience ENUM('all','department','selected') NOT NULL DEFAULT 'all',department VARCHAR(120) NULL,priority ENUM('normal','important') NOT NULL DEFAULT 'normal',scheduled_at DATETIME NULL,published_at DATETIME NULL,expires_at DATETIME NULL,created_by BIGINT UNSIGNED NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,INDEX(published_at),INDEX(expires_at))`);
  await db.query(`CREATE TABLE IF NOT EXISTS hrms_announcement_recipients (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,announcement_id BIGINT UNSIGNED NOT NULL,employee_id BIGINT UNSIGNED NOT NULL,read_at DATETIME NULL,acknowledged_at DATETIME NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_announcement_recipient(announcement_id,employee_id),INDEX(employee_id))`);
}
router.post('/', async (req,res,next)=>{try{await ensure(); if(!isAdmin(req))return res.status(403).json({success:false,message:'Admin access required'}); const {title,message,category='general',audience='all',department=null,employeeIds=[],priority='normal',scheduledAt=null,expiresAt=null}=req.body; if(!title?.trim()||!message?.trim())return res.status(400).json({success:false,message:'Title and message are required'}); const scheduled=new Date(scheduledAt); const publishAt=scheduledAt&&!Number.isNaN(scheduled.getTime())?scheduled:null; const [result]=await db.query('INSERT INTO hrms_announcements (title,message,category,audience,department,priority,scheduled_at,published_at,expires_at,created_by) VALUES (?,?,?,?,?,?,?,?,?,?)',[title.trim(),message.trim(),category,audience,department,priority,publishAt,publishAt&&publishAt>new Date()?null:new Date(),expiresAt||null,req.user.id]); let recipients=[]; if(audience==='selected')recipients=Array.isArray(employeeIds)?employeeIds:[]; else { const [rows]=await db.query(`SELECT id FROM employee_users WHERE is_active=1 ${audience==='department'&&department?'AND role=?':''}` ,audience==='department'&&department?[department]:[]); recipients=rows.map(r=>r.id); } if(recipients.length)await db.query('INSERT IGNORE INTO hrms_announcement_recipients (announcement_id,employee_id) VALUES '+recipients.map(()=>'(?,?)').join(','),recipients.flatMap(id=>[result.insertId,id])); res.status(201).json({success:true,data:{id:result.insertId,recipientCount:recipients.length}});}catch(e){next(e)}});
router.get('/', async(req,res,next)=>{try{await ensure();await db.query('UPDATE hrms_announcements SET published_at=scheduled_at WHERE published_at IS NULL AND scheduled_at IS NOT NULL AND scheduled_at<=NOW()'); if(!isAdmin(req))return res.status(403).json({success:false,message:'Admin access required'}); const [rows]=await db.query(`SELECT a.*,COUNT(r.id) recipient_count,SUM(r.read_at IS NOT NULL) read_count FROM hrms_announcements a LEFT JOIN hrms_announcement_recipients r ON r.announcement_id=a.id GROUP BY a.id ORDER BY COALESCE(a.published_at,a.created_at) DESC`); res.json({success:true,data:rows});}catch(e){next(e)}});
router.get('/employees',async(req,res,next)=>{try{await ensure();if(!isAdmin(req))return res.status(403).json({success:false,message:'Admin access required'});const [rows]=await db.query('SELECT id,full_name,staff_id,role FROM employee_users WHERE is_active=1 ORDER BY full_name');res.json({success:true,data:rows});}catch(e){next(e)}});
router.get('/:id/recipients', async (req,res,next) => {
  try { await ensure(); if (!isAdmin(req)) return res.status(403).json({success:false,message:'Admin access required'});
    const [rows] = await db.query('SELECT r.employee_id,e.full_name,e.staff_id,e.role,r.read_at,r.acknowledged_at FROM hrms_announcement_recipients r JOIN employee_users e ON e.id=r.employee_id WHERE r.announcement_id=? ORDER BY e.full_name',[req.params.id]);
    res.json({success:true,data:rows,summary:{recipients:rows.length,read:rows.filter(x=>x.read_at).length,unread:rows.filter(x=>!x.read_at).length}});
  } catch(e) { next(e); }
});router.get('/mine',async(req,res,next)=>{try{await ensure();await db.query('UPDATE hrms_announcements SET published_at=scheduled_at WHERE published_at IS NULL AND scheduled_at IS NOT NULL AND scheduled_at<=NOW()');const [rows]=await db.query(`SELECT a.*,r.read_at,r.acknowledged_at FROM hrms_announcement_recipients r JOIN hrms_announcements a ON a.id=r.announcement_id WHERE r.employee_id=? AND a.published_at IS NOT NULL AND a.published_at<=NOW() AND (a.expires_at IS NULL OR a.expires_at>NOW()) ORDER BY a.priority='important' DESC,a.published_at DESC`,[req.user.id]);res.json({success:true,data:rows});}catch(e){next(e)}});
router.patch('/:id/read',async(req,res,next)=>{try{await ensure();await db.query('UPDATE hrms_announcement_recipients SET read_at=COALESCE(read_at,NOW()) WHERE announcement_id=? AND employee_id=?',[req.params.id,req.user.id]);res.json({success:true});}catch(e){next(e)}});
module.exports=router;


