name: admin_web

description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1


environment:
  sdk: ^3.12.1



dependencies:

  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8


  # API
  dio: ^5.11.0
  http: ^1.6.0


  # Storage
  shared_preferences: ^2.5.5


  # File Upload
  file_picker: ^11.0.3
  desktop_drop: ^0.7.1
  cross_file: ^0.3.5+4


  # Excel Export
  excel: ^4.0.6


  # PDF Generate
  pdf: ^3.12.0


  # PDF Preview / Print
  printing: ^5.14.3


  # Download Files
  file_saver: ^0.4.0




dev_dependencies:

  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0




flutter:

  uses-material-design: true


  assets:
    - assets/images/