const TIME_ZONE=process.env.ATTENDANCE_TZ||'Asia/Kolkata',REQUIRED_MINUTES=Number(process.env.ATTENDANCE_REQUIRED_MINUTES||540);
const defaults={shiftStart:process.env.ATTENDANCE_SHIFT_START||'09:30:00',shiftEnd:process.env.ATTENDANCE_SHIFT_END||'18:30:00',lateAfter:process.env.ATTENDANCE_LATE_AFTER||'10:00:00',absentAfter:process.env.ATTENDANCE_ABSENT_AFTER||'12:00:00'};let settings={male:{...defaults},female:{...defaults}};
const key=g=>String(g||'').toLowerCase()==='female'?'female':'male',schedule=g=>settings[key(g)];
function partsInZone(date=new Date(),timeZone=TIME_ZONE){const p=new Intl.DateTimeFormat('en-GB',{timeZone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(date),v=t=>p.find(x=>x.type===t).value,y=v('year'),m=v('month'),d=v('day'),h=v('hour'),min=v('minute'),s=v('second');return{date:`${y}-${m}-${d}`,time:`${h}:${min}:${s}`,dateTime:`${y}-${m}-${d} ${h}:${min}:${s}`,hour:+h,minute:+min,second:+s}}
const todayIstDate=()=>partsInZone().date,nowIstDateTime=()=>partsInZone().dateTime,timeToSeconds=v=>{const p=String(v).split(':');return(+p[0]||0)*3600+(+p[1]||0)*60+(+p[2]||0)};
const isLateCheckIn=(d,g)=>timeToSeconds(String(d).slice(11,19))>timeToSeconds(schedule(g).lateAfter),isAbsentCheckIn=(d,g)=>timeToSeconds(String(d).slice(11,19))>timeToSeconds(schedule(g).absentAfter),isLateAt=(d,z)=>timeToSeconds(partsInZone(d,z).time)>timeToSeconds(settings.male.lateAfter),isAbsentAt=(d,z)=>timeToSeconds(partsInZone(d,z).time)>timeToSeconds(settings.male.absentAfter);
function minutesBetween(a,b){a=new Date(String(a).replace(' ','T'));b=new Date(String(b).replace(' ','T'));return isNaN(a)||isNaN(b)?0:Math.max(0,Math.round((b-a)/60000))}const isEarlyExit=m=>Number(m||0)<REQUIRED_MINUTES;
function formatDisplayTime(v){if(!v)return '-';const[h,m]=String(v).slice(11,19).split(':').map(Number);return String((h+11)%12+1).padStart(2,'0')+':'+String(m).padStart(2,'0')+' '+(h>=12?'PM':'AM')}function displayStatus(r){if(r.status==='on_leave')return'On Leave';if(r.status==='absent'||!r.checkInAt)return'Absent';if(r.checkOutAt&&isEarlyExit(minutesBetween(r.checkInAt,r.checkOutAt)))return'Early Exit';return r.isLate||r.status==='late'?'Late':'Present'}
function weekdayShort(d){const p=d.split('-').map(Number);return['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][new Date(Date.UTC(p[0],p[1]-1,p[2])).getUTCDay()]}function addDays(d,n){const p=d.split('-').map(Number),x=new Date(Date.UTC(p[0],p[1]-1,p[2])+n*864e5);return`${x.getUTCFullYear()}-${String(x.getUTCMonth()+1).padStart(2,'0')}-${String(x.getUTCDate()).padStart(2,'0')}`}function weekdaysForDate(d){const p=d.split('-').map(Number),w=new Date(Date.UTC(p[0],p[1]-1,p[2])).getUTCDay(),m=addDays(d,w===0?-6:1-w);return[0,1,2,3,4].map(n=>addDays(m,n))}
function normal(v,label){v=String(v||'').trim();if(!/^(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d)?$/.test(v))throw Error(`${label} must use HH:mm`);return v.length===5?`${v}:00`:v}function normalize(v,label){const n={shiftStart:normal(v.shiftStart,`${label} check-in time`),shiftEnd:normal(v.shiftEnd,`${label} check-out time`),lateAfter:normal(v.lateAfter,`${label} late-after time`),absentAfter:normal(v.absentAfter,`${label} absent-after time`)};if(timeToSeconds(n.lateAfter)<timeToSeconds(n.shiftStart))n.lateAfter=n.shiftStart;if(timeToSeconds(n.absentAfter)<timeToSeconds(n.lateAfter))n.absentAfter=n.lateAfter;return n}
async function add(db,d){try{await db.query(`ALTER TABLE hrms_attendance_time_settings ADD COLUMN ${d}`)}catch(e){if(e.code!=='ER_DUP_FIELDNAME')throw e}}async function ensureTimeSettings(db){await db.query('CREATE TABLE IF NOT EXISTS hrms_attendance_time_settings (id TINYINT PRIMARY KEY, shift_start TIME NOT NULL, shift_end TIME NOT NULL, late_after TIME NOT NULL, absent_after TIME NULL, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)');await add(db,'absent_after TIME NULL AFTER late_after');for(const g of['male','female'])for(const[k,c]of Object.entries({shiftStart:'shift_start',shiftEnd:'shift_end',lateAfter:'late_after',absentAfter:'absent_after'}))await add(db,`${g}_${c} TIME NOT NULL DEFAULT '${defaults[k]}'`);await db.query('INSERT IGNORE INTO hrms_attendance_time_settings (id,shift_start,shift_end,late_after,absent_after) VALUES (1,?,?,?,?)',[defaults.shiftStart,defaults.shiftEnd,defaults.lateAfter,defaults.absentAfter])}
async function getTimeSettings(db){await ensureTimeSettings(db);const[r]=await db.query('SELECT * FROM hrms_attendance_time_settings WHERE id=1'),x=r[0]||{};for(const g of['male','female'])settings[g]=normalize({shiftStart:x[`${g}_shift_start`]||x.shift_start||defaults.shiftStart,shiftEnd:x[`${g}_shift_end`]||x.shift_end||defaults.shiftEnd,lateAfter:x[`${g}_late_after`]||x.late_after||defaults.lateAfter,absentAfter:x[`${g}_absent_after`]||x.absent_after||defaults.absentAfter},g);return{male:{...settings.male},female:{...settings.female},...settings.male}}async function updateTimeSettings(db,v){await getTimeSettings(db);const n={male:normalize(v.male||v,'Male'),female:normalize(v.female||v,'Female')};await db.query('UPDATE hrms_attendance_time_settings SET male_shift_start=?,male_shift_end=?,male_late_after=?,male_absent_after=?,female_shift_start=?,female_shift_end=?,female_late_after=?,female_absent_after=? WHERE id=1',[n.male.shiftStart,n.male.shiftEnd,n.male.lateAfter,n.male.absentAfter,n.female.shiftStart,n.female.shiftEnd,n.female.lateAfter,n.female.absentAfter]);settings=n;return{male:{...n.male},female:{...n.female},...n.male}}
module.exports={TIME_ZONE,REQUIRED_MINUTES,partsInZone,todayIstDate,nowIstDateTime,isLateCheckIn,isLateAt,isAbsentCheckIn,isAbsentAt,minutesBetween,isEarlyExit,formatDisplayTime,displayStatus,weekdayShort,weekdaysForDate,getTimeSettings,updateTimeSettings,get LATE_AFTER(){return settings.male.lateAfter},get ABSENT_AFTER(){return settings.male.absentAfter},get SHIFT_START(){return settings.male.shiftStart},get SHIFT_END(){return settings.male.shiftEnd}};
